name: school
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.3
  google_fonts: ^1.0.0
  location: ^3.0.2
  adhan_flutter: ^0.0.2
  shared_preferences: ^0.5.7+3
  provider: ^4.0.5+1
  flutter_local_notifications: ^1.4.2
  rxdart: ^0.24.0
  font_awesome_flutter: ^8.8.1
  audioplayers: ^0.15.1
  google_maps_flutter: ^0.4.0




  cupertino_icons: ^0.1.2
  uuid: ^2.0.4
  intl: ^0.16.1
  http: ^0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true


  assets:
    - assets/images/omra.png
    - assets/images/back.png
    - assets/images/Rectangle.png
    - assets/images/Rectangle1.png
    - assets/images/acc.png
    - assets/images/hadj.png
    - assets/images/everything.png
    - assets/images/be.png
    - assets/images/quraan.png
    - assets/images/kaouther.png
    - assets/jsons/
    - assets/jsons/surah/
    - assets/jsons/translation/en/


  fonts:
    - family: AeCortoba
      fonts:
         - asset: fonts/ae_Cortoba.ttf
